// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCERuzDNWWcnvWI6v8FqGmhiisY04Cb0XY',
    appId: '1:516279397839:web:59e89a8666919e2db6f6ba',
    messagingSenderId: '516279397839',
    projectId: 'flutterapp-1234',
    authDomain: 'flutterapp-1234.firebaseapp.com',
    storageBucket: 'flutterapp-1234.firebasestorage.app',
    measurementId: 'G-BHYKYMCFGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSQR-mx_30YYGSKhTmfMN3Q1BgJNYt-qU',
    appId: '1:516279397839:android:d1fa7bf3c8ba09d3b6f6ba',
    messagingSenderId: '516279397839',
    projectId: 'flutterapp-1234',
    storageBucket: 'flutterapp-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0dvGl1OIf_JD3McEgqJocf8xN-2m2vDI',
    appId: '1:516279397839:ios:e21d84658c701beab6f6ba',
    messagingSenderId: '516279397839',
    projectId: 'flutterapp-1234',
    storageBucket: 'flutterapp-1234.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0dvGl1OIf_JD3McEgqJocf8xN-2m2vDI',
    appId: '1:516279397839:ios:e21d84658c701beab6f6ba',
    messagingSenderId: '516279397839',
    projectId: 'flutterapp-1234',
    storageBucket: 'flutterapp-1234.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCERuzDNWWcnvWI6v8FqGmhiisY04Cb0XY',
    appId: '1:516279397839:web:97015e054bb8fac1b6f6ba',
    messagingSenderId: '516279397839',
    projectId: 'flutterapp-1234',
    authDomain: 'flutterapp-1234.firebaseapp.com',
    storageBucket: 'flutterapp-1234.firebasestorage.app',
    measurementId: 'G-WSXP6RLBR0',
  );

}